### PR TITLE
Minor update of the exatract sample script to fix Travis issues

### PR DESCRIPTION
**Pull request by mewmew**

### CODE REVIEW

**Comment by Predelnik** [comment]
I wonder if shebang inside script will not work if `python` will be simply removed from the line, but I guess it doesn't matter that much anyway.

**Comment by mewmew** [comment]
> I wonder if shebang inside script will not work if python will be simply removed from the line, but I guess it doesn't matter that much anyway.

Not quite sure either, I tried a few different things to get it working with Travis, and when it finally started working I did not have the energy to check what could be removed. Should have, but, oh well. It's working well enough for now.

**Comment by Predelnik** [comment]
Yeah I see by the amount of commits 😅  Most of the time it's better to start with different branch when doing fixes like that in my experience.

**Comment by mewmew** [comment]
> Yeah I see by the amount of commits sweat_smile Most of the time it's better to start with different branch when doing fixes like that in my experience.

Yes, will keep it in mind for next time. I thought it would be just one commit to have it working ,possibly two. Boy was I wrong.

**Pull request merged**
